[workspace]
channels = ["conda-forge"]
name = "cerulean-forward"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
lab = "jupyter lab opendrift.ipynb"
notebook = "jupyter nbconvert --to notebook --execute --inplace opendrift.ipynb"
slides = "quarto render presentation.qmd"

[dependencies]
python = "==3.12"
opendrift = ">=1.14.8,<2"
jupyter = ">=1.1.1,<2"
quarto = ">=1.8.27,<2"
matplotlib = ">=3.5"
numpy = ">1.23"
scipy = ">=1.14"
netcdf4 = "*"
ffmpeg = "*"
pyproj = ">=2.3"
libgdal = ">=3.1"
gdal = ">=3.1"
xarray = "<=2025.9.0"
dask = "*"
geopandas = "*"
cfgrib = "*"
cf_xarray = "*"
pygrib = "*"
xhistogram = "*"
requests = "*"
cartopy = ">=0.20"
nc-time-axis = "*"
geojson = "*"
pynucos = ">=2.12"
isodate = "*"
coloredlogs = "*"
cmocean = "*"
utm = "*"
roaring-landmask = ">=0.7"
adios_db = ">=1.2,<1.2.7"
copernicusmarine = ">=2.0"
bottleneck = "*"
python-dotenv = "*"
pip = "*"
git = "*"

[pypi-dependencies]
trajan = { git = "https://github.com/OpenDrift/trajan.git" }
